controller_names:
  - dobot_arm_controller


dobot_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  defaulf: true
  joints: 
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
